version: "3.9"
services:
  punchr:
    image: dennistra/punchr-client:latest
    container_name: punchr_client
    restart: always
    user: punchr
    environment:
      # More option at pkg/client/app.go
      PUNCHR_CLIENT_API_KEY: # Add your API key here
    network_mode: host
